default_install_hook_types:
    # - pre-push # if you want to run before a push
- pre-commit
repos:
- repo: https://github.com/tekwizely/pre-commit-golang
  rev: v1.0.0-rc.1
  hooks:
  - id: go-build-mod
  - id: go-mod-tidy
  - id: go-test-mod
  - id: go-vet-mod
  - id: go-sec-mod
  - id: go-staticcheck-mod
  - id: go-structslop-mod
  - id: go-returns      # replaces go-imports & go-fmt
  - id: golangci-lint
